CREATE DATABASE WorkJournal
GO
USE WorkJournal
GO
CREATE TABLE Schedule (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[Subject] NVARCHAR(20) NULL,
	[WorkDateTime] DATETIME NULL,
	[CreateDateTime] DATETIME NOT NULL,
	[UpdateDateTime] DATETIME NULL,
	[IsDelete] INT NOT NULL DEFAULT(0),
);
GO
CREATE TABLE ScheduleItem (
	[Id] UNIQUEIDENTIFIER PRIMARY KEY,
	[ScheduleId] UNIQUEIDENTIFIER NOT NULL,
	[WorkItem] NVARCHAR(100) NULL,
	[WorkDuration] INT NOT NULL DEFAULT(0),
);